export const ADMIN_STUDENTS_REQUEST = 'ADMIN_STUDENTS_REQUEST'
export const ADMIN_STUDENTS_SUCCESS = 'ADMIN_STUDENTS_SUCCESS'
export const ADMIN_STUDENTS_FAIL = 'ADMIN_STUDENTS_FAIL' 

export const DELETE_STUDENTS_REQUEST = 'DELETE_STUDENTS_REQUEST'
export const DELETE_STUDENTS_SUCCESS = 'DELETE_STUDENTS_SUCCESS'
export const DELETE_STUDENTS_RESET = 'DELETE_STUDENTS_RESET'
export const DELETE_STUDENTS_FAIL = 'DELETE_STUDENTS_FAIL'

export const UPDATE_STUDENTS_REQUEST = 'UPDATE_STUDENTS_REQUEST'
export const UPDATE_STUDENTS_SUCCESS = 'UPDATE_STUDENTS_SUCCESS'
export const UPDATE_STUDENTS_RESET = 'UPDATE_STUDENTS_RESET'
export const UPDATE_STUDENTS_FAIL = 'UPDATE_STUDENTS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'